require:
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec_rails

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
