version: '3'

services:
  testdb:
    image: 'supabase/postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres
  # test_app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.test
  #   ports:
  #     - 5100:5100