version: '3'

# Using this with Docker Compose until I can get DO's container registry stuff up and running

services:
  app:
    # image: registry.digitalocean.com/robertbabaev/coursefull-app:latest
    build:
      context: .
    ports:
      - 3000:3000
    secrets:
      - op_service_account_token
  client:
    build:
      context: client
      secrets:
        - op_service_account_token
    ports:
      - 5100:5100
    secrets:
      - op_service_account_token
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - ASSET_URL=${ASSET_URL}
    depends_on:
      - app
    security_opt:
      - no-new-privileges:true

secrets:
  op_service_account_token:
    environment: OP_SERVICE_ACCOUNT_TOKEN

volumes:
  caddy_data:
  caddy_config:
